Change "SHOULD NEVER" to "MUST NOT"
w3c/browser-payment-api pull request #356
Opened 2016-12-01 06:17 UTC by ianbjacobs

“Should never” is strong enough that if that is what we mean, then
we should use the corresponding RFC 2119 language.

If we mean less than MUST NOT, then let’s say “SHOULD NOT.”

In this edit I swap in MUST NOT for SHOULD NEVER because I think the
intention is the same.

2016-12-02 06:56 UTC, marcoscaceres requested changes

2016-12-02 06:56 UTC, marcoscaceres commented on index.html
> +          The <a>user agent</a> must not share information about the user
NIT: MUST NOT

2016-12-02 06:58 UTC, marcoscaceres commented
Whoa,  the commit history on this PR is a bit screwy. 

🔥🚨🔥🚨🔥🚨🔥🚨
Whomever merges this, please make sure you  "squash and merge" and remove the garbage details in the commit history. 
🔥🚨🔥🚨🔥🚨🔥🚨

2016-12-02 07:08 UTC, sideshowbarker commented
> Whomever merges this, please make sure you "squash and merge" and remove the garbage details in the commit history.

I think it might need more than just "squash and merge". Not sure but I think some other changes in this branch have not been merged yet; for example https://github.com/w3c/browser-payment-api/pull/356/commits/385bf7d5d41c9326be0374113ddc8683cfaeeb2b.

So I think what should be done before this PR branch is merged is:

1. Strip all commits except https://github.com/w3c/browser-payment-api/pull/356/commits/f86f545c94cc36a76f5fd92f270fd67ba5600da4 (e.g., with a `git rebase -i gh-pages` and then annotating all the other commits with `d` to make git rewrite the branch history with those removed)
2. `git push -f  git@github.com:ianbjacobs/browser-payment-api.git gh-pages` to update the PR

2016-12-12 16:42 UTC, ianbjacobs commented
@marcoscaceres, can we drop this pull request and could you simply make the requested change?

2016-12-13 00:14 UTC, sideshowbarker commented
@ianbjacobs I have a change ready to push to this PR, but when I tried to push it back to your branch, I got a “permission denied” error.

Can you go to the bottom right-hand side of https://github.com/w3c/browser-payment-api/pull/356 in the GitHub Web UI and make sure the “Allow edits from maintainers” option is checked?

2016-12-13 01:48 UTC, ianbjacobs commented
@sideshowbarker, now checked

2016-12-13 02:17 UTC, sideshowbarker commented
> @sideshowbarker, now checked

Thanks—OK, I just now force-pushed to update the PR, so @marcoscaceres can merge this

2016-12-13 02:21 UTC, sideshowbarker commented on index.html
> +          The <a>user agent</a> must not share information about the user
> NIT: MUST NOT

Fixed

2016-12-13 20:17 UTC, marcoscaceres approved these changes

2016-12-13 20:31 UTC, merged