Move state transitions diagram into a note
w3c/browser-payment-api pull request #406
Opened 2017-01-20 23:39 UTC by domenic

Closes #342.

2017-01-23 05:12 UTC, marcoscaceres requested changes
@domenic, let me know if you want me to do this (add figure/figcaption). I don't mind.

2017-01-23 05:12 UTC, marcoscaceres commented on index.html
> +          </p><img alt=
Why not use a figure/figcaption here? All the alt info seems valuable to everyone.

2017-01-23 05:16 UTC, domenic commented on index.html
> +          </p><img alt=
It's strictly redundant with the image, describing the exact same information.

2017-01-23 05:17 UTC, domenic commented on index.html
> +          </p><img alt=
If you think we should repeat it, then we need to do `alt=""` since then the image is redundant.

2017-01-23 05:29 UTC, marcoscaceres commented on index.html
> +          </p><img alt=
yeah, the alt is redundant... don't want to repeat it. Sorry for not being clear.

2017-01-30 09:21 UTC, marcoscaceres approved these changes
I'll add fig caption if/when I do another pass of at fixing the markup.

2017-01-30 09:21 UTC, merged