l10n: adds Localizable dict + TextDirection enum (closes #327)
w3c/browser-payment-api pull request #455
Opened 2017-03-14 00:34 UTC by marcoscaceres

2017-03-14 00:36 UTC, marcoscaceres commented
WIP, seeking feedback. It's just missing a statement about how to use the information when presenting the strings in a UI.

2017-03-14 00:39 UTC, marcoscaceres commented on index.html
> +        dictionary PaymentDetailsBase : Localizable {
I want this to apply to `PaymentDetailsUpdate.error`, which is why  put it here.

2017-03-14 00:42 UTC, marcoscaceres commented on index.html
> +          <a>PaymentDetailsUpdate</a> can contain a human-readable message in
I'm using "human-readable" as the key that binds together all these "localizable" members. Need to formally define "human-readable" as being potentially affected by dir/lang when present.

2017-03-14 00:44 UTC, marcoscaceres commented on index.html
> +          <a>PaymentDetailsUpdate</a> can contain a human-readable message in
("human-readable" was already in use in the spec, which is why I reused it - maybe we can come up with something nicer)

2017-03-14 03:25 UTC, domenic commented
Would be good to land after https://github.com/w3c/browser-payment-api/pull/451 to avoid conflicts.

Notably this does not allow serving up multiple options with different locales and allowing the browser to choose between them. I guess that is a non-goal.

It's also noteworthy that this matches NotificationOptions already, so that's good. Maybe we can consolidate this `Localizable` type into Web IDL or similar. /cc @annevk @beverloo @tobie. Notifications defaults `lang` to `""` BTW to represent, I guess, no language selected. That makes sense.

Also, this standard says it represents a BCP 47 language tag, but that's not quite accurate; a developer could pass in "asdf" and there's no normative text rejecting that. You'll instead want something similar to the verbiage at https://notifications.spec.whatwg.org/#language.

2017-03-14 04:50 UTC, marcoscaceres commented
> Notably this does not allow serving up multiple options with different locales and allowing the browser to choose between them. I guess that is a non-goal.

Yeah. Non-goal I think. 

> It's also noteworthy that this matches NotificationOptions already, so that's good. Maybe we can consolidate this Localizable type into Web IDL or similar. /cc @annevk @beverloo @tobie.

I was thinking the same.... would be great to have this in Web IDL.  Maybe we can craft `Localizable` here first, and then push it to WebIDL? 

>  Notifications defaults lang to "" BTW to represent, I guess, no language selected. That makes sense.

Will fix. 

> Also, this standard says it represents a BCP 47 language tag, but that's not quite accurate; a developer could pass in "asdf" and there's no normative text rejecting that. You'll instead want something similar to the verbiage at https://notifications.spec.whatwg.org/#language.

Yeah, that's some good wording.

2017-03-14 07:26 UTC, annevk commented
Uplifting to IDL seems reasonable. We already put some shared concepts and processing models there.

2017-03-14 09:50 UTC, tobie commented
Yeah, seems this could go in [§4 Common definitions](https://heycam.github.io/webidl/#common).

2017-03-14 15:13 UTC, ianbjacobs commented
@domenic wrote:

"Notably this does not allow serving up multiple options with different locales and allowing the browser to choose between them."

If I understand your comment, it is about support for multiple strings in multiple languages.
A long time back we discussed whether the API needed to support this. Our conclusion at the time was that it did not, because people could adjust content based on global directives like HTTP language negotiation.

(If you were talking about something else; sorry for the noise.)

Ian

2017-03-14 15:20 UTC, domenic commented
Yeah, it makes sense. So this is mostly about allowing people to markup certain messages as having a different lang/dir than the rest of the content on the page.

2017-03-15 12:03 UTC, zcorpan commented on index.html
> +          Directionality is determined by the [[!BIDI]] algorithm.
The bidi algorithm should be used for `ltr` and `rtl` as well... right?

I think we basically want to hook into http://www.unicode.org/reports/tr9/#Explicit_Directional_Isolates similarly to what CSS does in https://drafts.csswg.org/css-writing-modes-3/#unicode-bidi (for `isolate` or `plaintext` -- not sure which is more appropriate here).

2017-03-15 12:06 UTC, zcorpan commented
cc @w3c/i18n-reviewers

2017-03-15 16:41 UTC, annevk commented on index.html
> +          Directionality is determined by the [[!BIDI]] algorithm.
https://notifications.spec.whatwg.org/#direction has the text you need for this.

2017-03-16 08:29 UTC, marcoscaceres commented on index.html
> +          Directionality is determined by the [[!BIDI]] algorithm.
Thanks, will try to draft it soon.

2017-04-24 22:06 UTC, domenic requested changes

2017-04-24 22:06 UTC, domenic commented on index.html
> +        dictionary PaymentDetailsBase : Localizable {
I don't think it should go here if it only applies to PaymentDetailsUpdate. Instead you're going to have to just duplicate the two things (or use a partial dictionary PaymentDetailsUpdate).

If you put it here then PaymentDetailsInit gets it, and in particular that means passing `{ get dir() { throw new Error("boo"); }` to places that expect a PaymentDetailsInit must throw.

2017-04-24 22:06 UTC, domenic commented on index.html
> +        the human-readable members is by default:
This sentence doesn't make sense to me.

2017-05-02 09:38 UTC, marcoscaceres commented
blocked on https://github.com/heycam/webidl/pull/358

2017-05-02 09:50 UTC, marcoscaceres commented
argh, that's not right. Seems I screwed up a rebase.

2017-05-02 10:01 UTC, marcoscaceres commented
better...

2017-05-04 06:20 UTC, marcoscaceres commented
Still blocked on discussions over in the WebIDL repo. Probably take another few days to resolve those.

2017-05-04 06:54 UTC, tobie commented on index.html
> +            "!WEBIDL-LS#dfn-typedef">typedef</a> is defined by [[!WEBIDL-LS]].
You can go ahead and just use [[WEBIDL]], btw.

2017-05-04 07:02 UTC, marcoscaceres commented on index.html
> +            "!WEBIDL-LS#dfn-typedef">typedef</a> is defined by [[!WEBIDL-LS]].
Will fix globally! Thanks!

2017-05-04 12:31 UTC, zcorpan commented on index.html
> +            "!WEBIDL-LS#dfn-typedef">typedef</a> is defined by [[!WEBIDL-LS]].
[[WEBIDL]] is informative reference, [[!WEBIDL]] is normative reference.

2017-05-04 12:36 UTC, tobie commented on index.html
> +            "!WEBIDL-LS#dfn-typedef">typedef</a> is defined by [[!WEBIDL-LS]].
I meant WEBIDL vs WEBIDL-LS, sorry if that caused confusion. :(((

2017-05-05 01:13 UTC, marcoscaceres commented on index.html
> +            "!WEBIDL-LS#dfn-typedef">typedef</a> is defined by [[!WEBIDL-LS]].
It's all good. I sent https://github.com/w3c/browser-payment-api/pull/524

2017-08-31 06:06 UTC, marcoscaceres commented
Closing for now... will reopen if we want to add this in v2

2017-08-31 06:06 UTC, closed without merging