Editorial changes
w3c/browser-payment-api pull request #465
Opened 2017-03-20 16:12 UTC by ianbjacobs

Some editorial changes:

 * Payment methods describe data; they are not participants in a transaction.
   Therefore, recast the description of parties as payers/payees/providers
   of payment methods. (Both in Intro and Goals)

 * The word "buyer" was used in the intro and not used elsewhere in the
   spec. Therefore, I use payer/payee which are used further down.

 * The first examples the reader should encounter in the PaymentRequest
   interface description should be those most likely found in practice.
   The "Buy" button should come first. The other examples of in-app
   and POS are much further out and so I have listed them after.

 * Updated example 2 as follows:

   - We have network id values; we should use those instead of fictitious
     ones.

   - bobpay.com does not confirm (I believe) to the PMI spec. So I have
     used an example URL instead.

2017-03-20 22:40 UTC, marcoscaceres requested changes
Please run tidy over the doc

2017-03-20 22:56 UTC, ianbjacobs commented
@marcoscaceres,

I have just installed HTML Tidy version 5.5.10. What options should I run it with? I used '-i' but the result seems very different from the input file. That is: a lot more is changed by tidy than I changed via my edit. Please advise.

Ian

2017-03-20 23:04 UTC, marcoscaceres commented
@ianbjacobs, run:

```
tidy -config tidyconfig.txt -o index.html index.html
```

2017-03-21 00:28 UTC, marcoscaceres requested changes

2017-03-21 00:28 UTC, marcoscaceres commented on index.html
> +	<li>the payee, such as a merchant with an online store,</li>
I'd prefer these ended in full stop.

2017-03-21 00:28 UTC, marcoscaceres commented on index.html
> +	<li>the payee, such as a merchant with an online store,</li>
*each of these

2017-03-21 00:28 UTC, marcoscaceres commented on index.html
> +        <li>the payee, such as a merchant with an online store,
I'd still like this to be:

 * The payee: bla bla bla. 
 * The payer: bla bla bla.
 * The provider: bla bla bla.

2017-03-21 00:36 UTC, marcoscaceres approved these changes

2017-03-21 00:38 UTC, merged