Clarify wording to not imply 'pull' only payhments
w3c/browser-payment-api pull request #474
Opened 2017-03-24 12:38 UTC by mattsaxon

Some minor wording changes to make it clear that a paymentrequest may
actually process a transaction rather than just supply credentials

2017-03-28 02:07 UTC, marcoscaceres requested changes

2017-03-28 02:07 UTC, marcoscaceres commented on index.html
> +          has been processed. This data is returned by the <a>payment method</a>
Can you please rewrite this to use active voice.

2017-03-30 19:01 UTC, ianbjacobs commented on index.html
> +          has been processed. This data is returned by the <a>payment method</a>
Proposed:

            An object that provides information enabling the merchant to process or validate a transaction (depending on the <a>payment method</a>).

2017-07-18 05:52 UTC, marcoscaceres approved these changes
As this is editorial, I'm approving in the interest of moving this forward.

2017-07-18 05:53 UTC, marcoscaceres commented
@mattsaxon could you please rebase this?

2017-09-01 02:01 UTC, marcoscaceres commented
this part of the spec already changed. Please send a new PR if you think it's still not clear.

2017-09-01 02:01 UTC, closed without merging

2017-09-01 15:21 UTC, ianbjacobs commented
New pull request:
https://github.com/w3c/payment-request/pull/599