editorial: grouped payment details dictionaries into section
w3c/browser-payment-api pull request #479
Opened 2017-03-24 18:47 UTC by kayakalan

closes #427

2017-03-24 18:49 UTC, marcos-travel requested changes

2017-03-24 18:49 UTC, marcos-travel commented on index.html
> +    <meta name="generator" content=
Need to remove this.

2017-03-31 04:28 UTC, marcoscaceres commented
Marked as non-substantive for IPR from ash-nazg.

2017-03-31 04:30 UTC, marcoscaceres commented
Going to merge this, and then remove the tidy mark locally. The indentation risk merge conflicts if this sits for too long.

2017-03-31 04:30 UTC, merged

2017-03-31 05:23 UTC, kayakalan commented
Sorry to be slacker. High in the queue to get better and quicker at this.
Thx for the ping.

On Mar 30, 2017 9:30 PM, "Marcos Cáceres" <notifications@github.com> wrote:

Going to merge this, and then remove the tidy mark locally. The indentation
risk merge conflicts if this sits for too long.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/w3c/browser-payment-api/pull/479#issuecomment-290613168>,
or mute the thread
<https://github.com/notifications/unsubscribe-auth/AWahaHHuhKDdDVQcga5V3wxjAVcfLmB9ks5rrIFTgaJpZM4MooyG>
.

2017-03-31 05:31 UTC, marcoscaceres commented
@kayakalan, no probs. I already took care of it. Thanks for helping out with this. If you want to grab a few more editorial ones, go for it. Again, happy to provide guidance as needed.