Edits for issue 481
w3c/browser-payment-api pull request #506
Opened 2017-04-07 14:10 UTC by ianbjacobs

- new goal about streamlined user experience
- neutralize pref language

https://github.com/w3c/browser-payment-api/issues/481

Based on WPWG teleconf discussion
http://www.w3.org/2017/04/06-wpwg-minutes

2017-04-10 23:51 UTC, marcoscaceres commented
@ianbjacobs, seems your version of tidy is different from the one we've been using. Make sure you have the latest from http://www.html-tidy.org/ or `brew install tidy-html5`. You should be on version 5.4.0.

2017-04-10 23:52 UTC, marcoscaceres requested changes
Can't view changes because of tidy.

2017-04-10 23:52 UTC, marcoscaceres commented
Also, make sure you run:

```
tidy -config tidyconfig.txt -o index.html index.html
```

2017-04-11 03:01 UTC, ianbjacobs commented
Hi @marcoscaceres,

I updated tidy (now 5.4.0) and ran it. Cheers!

Ian

2017-04-11 07:32 UTC, marcoscaceres commented
@ianbjacobs, really sorry for the pain, but it's still not quite right. It seems you still have version 5.2 - and it didn't pick up our configuration file. Please make sure you run:

```BASH
tidy -config tidyconfig.txt -o index.html index.html
```

2017-04-11 07:33 UTC, marcoscaceres requested changes

2017-04-11 07:33 UTC, marcoscaceres commented on index.html
> +    "HTML Tidy for HTML5 for Mac OS X version 5.2.0">
Tidy mark should not be here.

2017-04-11 12:59 UTC, ianbjacobs commented
Hi @marcoscaceres,

Apparently tidy:no-mark does not cause a meta element to be removed if it is already there. It merely suppresses adding one if it is not there. I didn't realize this. I removed it by hand. (I confirm I have Tidy 5.4.)

2017-04-12 20:31 UTC, zkoch commented
Barring issues with tidy, the text here LGTM

2017-04-20 14:30 UTC, mattsaxon commented
With the revised spec text;
150 + Enable user agents to streamline the users's payment experience  
151 + by taking into account user preferences, merchant information,  
152 + security considerations, and other factors.  

Whilst it is clear to me how the other factor are exposed to the user-agent, there seems to me to be no way of the merchant expressing their preference.

I propose we make explicit that the ordering of the PMIs is that expression, but that we make no statement about the behaviour of the user-agent with regard to this ordering.

2017-04-20 14:40 UTC, mountainhippo commented
That would be a good compromise for me. Appreciate we are walking a tightrope but we need to be able to provide a hint for merchant preference to maintain a capability that merchants have today

2017-04-27 01:05 UTC, marcoscaceres requested changes

2017-04-27 01:05 UTC, marcoscaceres commented on index.html
> +          <li>Enable user agents to streamline the users's payment experience
nit: s/users's/users'

2017-04-27 01:05 UTC, marcoscaceres commented on index.html
> +          sequence of payment method selection). The fact that a successful
"sequence" is problematic, because there is already WebIDL sequence defined.

2017-04-27 21:43 UTC, closed without merging

2017-04-27 21:47 UTC, ianbjacobs commented
I don't think I closed this...not sure what happened.

2017-04-27 22:48 UTC, marcoscaceres commented
The commit history vanished?

2017-04-27 23:32 UTC, ianbjacobs commented
Did I screw something up (in GitHub)? :(

If so I am sorry. :(

Ian

2017-04-28 00:19 UTC, marcoscaceres commented
I'm not sure - but no stress: just looks like the commits in the branch vanished. Let's see if we can get them back so not to lose the changes. Im on my phone right now - will send you some magic git commands once I get to work.

2017-07-10 14:55 UTC, ianbjacobs commented
@mattsaxon, I believe you and Ken chatted about this. Based on that conversation are you satisfied with the closing of this issue with language as-is?

Ian