Reject with SecurityError if the UA rejects the call to show().
w3c/browser-payment-api pull request #512
Opened 2017-04-27 01:30 UTC by adrianba

Fixes #486.

2017-04-27 18:40 UTC, domenic commented
I have some editorial tweaks; @adrianba could you check the box "allow edits from maintainers"? See https://help.github.com/assets/images/help/pull_requests/allow-maintainers-to-make-edits-sidebar-checkbox.png

Note that unlike the "AbortError" case below, this does not close down the PaymentRequest and prevent further use of it. That seems good and intentional, but I wanted to make sure people were aware of the difference.

2017-05-05 02:11 UTC, marcoscaceres requested changes
@adrianba, see @domenic's comments. Would like to see his tweaks before adding mine.

2017-05-10 22:23 UTC, marcoscaceres commented
@domenic, should be good now. @adrianba clicked the box.

2017-05-10 22:38 UTC, domenic approved these changes
My tweaks applied; over to Marcos

2017-05-11 04:23 UTC, marcoscaceres requested changes
One small change.

2017-05-11 04:23 UTC, marcoscaceres commented on index.html
> +            <p>
This should be a Note, stating that: "During the Candidate Recommendation phase, implementations are expected to experiment in this area..." 

And concluding with: "If interoperable behavior emerges amongst user agents, then that behavior will be standardized here before progressing the specification along the W3C Recommendation Track."

2017-05-15 07:58 UTC, marcoscaceres commented
@adrianba please check the box again if you want me to make the modifications I suggested.

2017-05-31 22:36 UTC, marcoscaceres approved these changes
Approving and merging to avoid bit-rot. Will add the suggestions I made in a new PR.

2017-05-31 22:37 UTC, merged