editorial: s/web page/developers and s/the developer/developers
w3c/browser-payment-api pull request #527
Opened 2017-05-09 07:31 UTC by bentian

Fixes #437

2017-05-09 07:45 UTC, marcoscaceres requested changes
Some of these need to be changed to singular: either "a developer" or "the developer", where it makes sense.

2017-05-09 07:45 UTC, marcoscaceres commented on index.html
> +          <a>PaymentResponse</a> returned to developers but before developers
this one should probably be phrased in terms of the caller or script.

2017-05-09 07:45 UTC, marcoscaceres commented on index.html
> +          returned. However, if something goes wrong and developers never call
this one needs to be singular.

2017-05-09 07:45 UTC, marcoscaceres commented on index.html
> +        Developers create a <a>PaymentRequest</a> to make a payment request.
Singular here.

2017-05-09 07:45 UTC, marcoscaceres commented on index.html
> +                  informing developers that each <a>payment method</a> needs
singular here. Check the others. Might make more sense as just "the developer"

2017-05-09 07:45 UTC, marcoscaceres commented on index.html
> +            options developers wish to use from the payment request system.
Maybe: "...information the developer needs from the end-user to perform the payment (e.g., the person's name and shipping address)."

2017-05-09 07:45 UTC, marcoscaceres commented on index.html
> +              developers that at least one <a>payment method</a> is required.
singular here.

2017-05-09 07:45 UTC, marcoscaceres commented on index.html
> +              developers that the total can't be negative.
same here..

2017-05-09 07:45 UTC, marcoscaceres commented on index.html
> +              optionally informing developers that the value is invalid.
same...

2017-05-09 07:45 UTC, marcoscaceres commented on index.html
> +            The <a>show()</a> method is called when developers want to begin
"a developer"

2017-05-09 07:53 UTC, dontcallmedom commented
Marked as non-substantive for IPR from ash-nazg.

2017-05-09 08:52 UTC, dontcallmedom commented
Marked as non-substantive for IPR from ash-nazg.

2017-05-10 07:04 UTC, marcoscaceres requested changes
Nearly there.

2017-05-10 07:04 UTC, marcoscaceres commented on index.html
> +          If developers wish to update the payment request then they should
I feel like this one should be singular, but stick with gender neutral "they". Also, we shouldn't say "should" there... also, wish is kinda vague (I know it's not your wording, but let's fix it now :)). So:

> If a developer wants to update the payment request, then they need to

2017-05-10 07:04 UTC, marcoscaceres commented on index.html
> +            The <a>abort()</a> method is called if developers wish to tell
change this to singular, to match the note above.

2017-05-10 07:21 UTC, bentian commented on index.html
> +          If developers wish to update the payment request then they should
So there would be inconsistency between _the developer_ and _they_. Is this a convention for gender neutrality?

2017-05-10 08:17 UTC, marcoscaceres commented on index.html
> +          If developers wish to update the payment request then they should
yes, that's a convention.

2017-05-10 23:58 UTC, marcoscaceres approved these changes
Lgtm. Thanks Ben!

2017-05-10 23:59 UTC, merged