editorial: cleanup of updateWith()
w3c/browser-payment-api pull request #533
Opened 2017-05-22 07:34 UTC by marcoscaceres

2017-05-22 19:00 UTC, domenic requested changes

2017-05-22 19:00 UTC, domenic commented on index.html
> +                            string. Rethrow any exceptions.
This needs to "abort the update", not rethrow the exception.

2017-05-22 23:49 UTC, marcoscaceres commented on index.html
> +                            string. Rethrow any exceptions.
oops!

2017-05-23 00:33 UTC, domenic approved these changes

2017-05-23 00:52 UTC, merged