Editorial changes
w3c/browser-payment-api pull request #559
Opened 2017-07-10 21:46 UTC by ianbjacobs

Hi Editors,

Here are some small editorial suggestions.

I also have some questions upon rereading the spec:

 * The phrase "settle" a promise first appears in 16.2.1 updateWith().
   It is not used elsewhere in the document. Should it be changed to
   be consistent with usage elsewhere in the document?

 * I would have expected information about testing and CR exit
   criteria in the status section, not the section on conformance.
  After CR it will no longer be useful in the section on conformance.
  Would you consider moving this information to the status section?
 
Thanks!

Ian

2017-07-11 20:25 UTC, adrianba commented
> * The phrase "settle" a promise first appears in 16.2.1 updateWith().
It is not used elsewhere in the document. Should it be changed to
be consistent with usage elsewhere in the document?

This is the only place where a developer provides a promise that needs to be settled.

2017-07-11 21:07 UTC, ianbjacobs commented
@adrianba wrote:

"This is the only place where a developer provides a promise that needs to be settled."

Ok, then it's a term of art that I didn't know. I see @domenic has written about it:
 https://github.com/domenic/promises-unwrapping/blob/master/docs/states-and-fates.md

Sorry for the noise,

Ian

2017-07-17 04:10 UTC, marcoscaceres requested changes

2017-07-17 04:10 UTC, marcoscaceres commented on index.html
> +          may take place at a time. The <a>user agent</a> user interface should
Please revert this, as it introduces a MAY. Also, when implementing, the original is more clear - as it's converted to an `assert()` in each implementation.

2017-07-17 04:10 UTC, marcoscaceres commented on index.html
> +            further action. The <a>user agent</a> user interface should ensure
Please also revert this one - as above.

2017-07-17 04:10 UTC, marcoscaceres commented on index.html
> +        interfaces may confuse the user, this specification limits the <a>user
s/may/might (we try not avoid putting conformance requirements on users in this spec)

2017-07-17 04:10 UTC, marcoscaceres commented on index.html
> +        global to the browser and initially false.
Please remove the ", global to the browser and initially false." Avoids duplication.

2017-07-17 04:10 UTC, marcoscaceres commented on index.html
> +          <p>
s/`<p>`/`<p class="note">`

2017-07-17 04:10 UTC, marcoscaceres commented on index.html
> +        with deployed software.
s/deployed software/existing content on the Web.

2017-07-17 04:10 UTC, marcoscaceres commented on index.html
> +      <p class="note">
This should only appear once in the document. I suggest dropping this one.

2017-07-17 13:44 UTC, ianbjacobs commented on index.html
> +          may take place at a time. The <a>user agent</a> user interface should
Hi Marcos,

Just a note that my proposal does not introduce the word MAY. The proposed sentence is: "The <a>user agent</a> user interface should ensure that this never occurs." The replaced sentence was "This should never occur."

Here's why I propose the change:

* Cnsistency with 5 instances of that sentence elsewhere in the document. (There are 2
instances of the replaced sentence in the document, so I went with the majority formulation.)
* I think that formulating this as a user agent responsibility is more useful than stating existentially
that something should not occur.

Ian

P.S. I will update the pull request to take into account your other suggestions.

2017-07-17 13:45 UTC, ianbjacobs commented on index.html
> +            further action. The <a>user agent</a> user interface should ensure
See above clarification (so not yet reverting).

2017-07-17 13:49 UTC, ianbjacobs commented on index.html
> +      <p class="note">
I removed the latter of the 2 instances (leaving the first one earlier in the document).

2017-07-18 02:08 UTC, marcoscaceres commented on index.html
> +          may take place at a time. The <a>user agent</a> user interface should
I concur.

2017-07-18 02:08 UTC, marcoscaceres approved these changes

2017-07-18 02:09 UTC, marcoscaceres commented on index.html
> +          may take place at a time. The <a>user agent</a> user interface should
Actually, maybe just drop "user interface".

2017-07-18 02:10 UTC, marcoscaceres requested changes

2017-07-18 02:10 UTC, marcoscaceres commented on index.html
> +            further action. The <a>user agent</a> user interface should ensure
as above.

2017-07-18 02:23 UTC, ianbjacobs commented
Hi Marcos, I made the final requested change (deleted "user interface").

Ian

2017-07-18 04:00 UTC, marcoscaceres approved these changes

2017-07-18 04:02 UTC, merged