validate PaymentCurrencyAmount.currency (closes #490)
w3c/browser-payment-api pull request #567
Opened 2017-07-31 05:22 UTC by marcoscaceres

* Hooks into ECMAScript's Intl's `IsWellFormedCurrencyCode`.
* Internally changes currencies into canonical form (upper case).
* Groups checking and normalization algorithms for "is valid amount" and "is valid total" - reducing a fair bit of spec text. 
* Relocates "valid decimal monetary value" to `PaymentCurrencyAmount`.
* Cites [[ECMASCRIPT]], instead of obsolete [[ECMA-262-2015]].

2017-07-31 08:38 UTC, marcoscaceres commented
Tests incoming also

2017-08-01 03:41 UTC, domenic requested changes
Great simplification and consolidation. Some issues with the algorithm prose though.

2017-08-01 03:41 UTC, domenic commented on index.html
> +                <a>Check and canonicalize <var>total</var></a>. Rethrow any
I'm a little weirded out by how the variable name is both a variable name and part of the algorithm name. IMO "[Check and canonicalize the total] _total_" would be better.

2017-08-01 03:41 UTC, domenic commented on index.html
> +                exceptions.
In theory rethrowing exceptions is not necessary (https://infra.spec.whatwg.org/#algorithm-control-flow), but in practice we should stay consistent, and I believe the spec mostly includes this verbiage right now. So, just noting FYI.

2017-08-01 03:41 UTC, domenic commented on index.html
> +                <a>Check and canonicalize <var>total</var></a>. Rethrow any
This would also allow you to avoid the intermediate variables that have been inserted in various places.

2017-08-01 03:41 UTC, domenic commented on index.html
> +              in <var>paymentMethod</var> tuple.
While here: "**item** in **the** paymentMethod tuple"

2017-08-01 03:41 UTC, domenic commented on index.html
> +            for formatting.
Last sentence is messed up; should be either "a user agent should" or "should be used", not both.

2017-08-01 03:41 UTC, domenic commented on index.html
> +          the amount is negative.
In Infra we've moved toward omitting the spelled out name, so you'd just do `U+002D (-)` these days. See https://infra.spec.whatwg.org/#code-points

2017-08-01 03:41 UTC, domenic commented on index.html
> +          <li>let <var>isValidCurrency</var> be the result of calling
Uppercase "let"

2017-08-01 03:41 UTC, domenic commented on index.html
> +          <li>If <var>isValidCurrency</var> returns false, then throw a
s/returns/is/

2017-08-01 03:41 UTC, domenic commented on index.html
> +          <li>If <a>currencySystem</a> is not
It should be _amount_.currencySystem. Same for `currency` and "_amount_'s `value`" below.

2017-08-01 03:41 UTC, domenic commented on index.html
> +          <code>urn:iso:std:iso:4217</code>, terminate this algorithm.
This is a string, so needs quotes around it.

2017-08-01 03:41 UTC, domenic commented on index.html
> +          </li>
This is written a little ambiguously. I'd prefer "Set _amount_.currency to the result of [ASCII uppercasing](https://infra.spec.whatwg.org/#ascii-uppercase) _amount_.currency". (Or is ASCII uppercasing incorrect here? In which case we should pick a well-defined uppercasing algorithm.)

2017-08-01 03:41 UTC, domenic commented on index.html
> +          HYPHEN-MINUS, then throw a <a>TypeError</a> optionally informing the
RangeError seems better? But maybe not worth the churn at this stage.

2017-08-01 05:06 UTC, marcoscaceres commented
Tests: https://github.com/w3c/web-platform-tests/pull/6670

2017-08-01 05:14 UTC, marcoscaceres commented on index.html
> +          HYPHEN-MINUS, then throw a <a>TypeError</a> optionally informing the
Yeah, let's leave this one... it be a pain to change it now.

2017-08-01 05:24 UTC, marcoscaceres commented on index.html
> +            for formatting.
Woops... this unhelpful anyway. I did some research, and what we actually want here is "SHOULD use U+00A4 (¤)" - which is the the generic currency sign: https://en.wikipedia.org/wiki/Currency_sign_(typography)

2017-08-01 05:29 UTC, marcoscaceres commented on index.html
> +          </li>
ASCII uppercasing is correct.

2017-08-01 05:37 UTC, marcoscaceres commented
Just noting the tests only cover constructor. Need to make a bunch of manual tests for `updateWith()`.

2017-08-01 05:53 UTC, marcoscaceres commented on index.html
> +                <a>Check and canonicalize <var>total</var></a>. Rethrow any
Fixing this now...

2017-08-01 06:00 UTC, marcoscaceres commented on index.html
> +          the amount is negative.
I fixed these globally also to match infra.

2017-08-01 06:08 UTC, marcoscaceres commented on index.html
> +                exceptions.
Yeah, the rethrow is a bit redundant - we need some kind of spec/platform convention whereby if algorithm name starts with the word "X", it potentially throw.

Maybe we already have that for these kinds of checker/validator algorithms?

2017-08-02 00:48 UTC, domenic approved these changes
LGTM with nits

2017-08-02 00:48 UTC, domenic commented on index.html
> +          <var>total</var> <a>PaymentCurrencyAmount</a></dfn>, run the
This should be `<dfn>check and canonicalize total</dfn> given a <a>PaymentCurrencyAmount</a> <var>total</var>`, I think.

(Same for the "amount" version)

2017-08-02 00:48 UTC, domenic commented on index.html
> +          <li>Let <var>value</var> be <var>amount</var>.<a>value</a>.
Unsure this intermediate `value` variable is helpful.

2017-08-02 00:48 UTC, domenic commented on index.html
> +          <code>urn:iso:std:iso:4217</code>, terminate this algorithm.
Missing quotes here

2017-08-02 00:48 UTC, domenic commented on index.html
>          </dt>
Above this line, it says "ECMA-262 6th Edition, The ECMAScript 2015 Language Specification", but probably it should say "ECMAScript" or "The ECMAScript Language Specification" or similar.

2017-08-02 03:02 UTC, marcoscaceres commented on index.html
>          </dt>
Went with ECMAScript.

2017-08-02 03:03 UTC, merged

2017-08-02 03:26 UTC, marcoscaceres commented
Huge thanks for the review, @domenic! Much improved.