Added information about redactList to privacy consideration
w3c/browser-payment-api pull request #738
Opened 2018-06-26 22:32 UTC by ianbjacobs

…about not exposing user information, part of
https://github.com/w3c/payment-request/issues/675

The following tasks have been completed:

 * [ ] Confirmed there are no ReSpec errors/warnings.
 * [ ] Added Web platform tests (link)
 * [ ] added MDN Docs (link)
 * [ ] added MDN [compat data](https://github.com/mdn/browser-compat-data)

Implementation commitment:

 * [ ] Safari (link to issue)
 * [ ] Chrome (link to issue)
 * [ ] Firefox (link to issue)
 * [ ] Edge (public signal)

Impact on Payment Handler spec?

2018-06-28 15:43 UTC, marcoscaceres requested changes

2018-06-28 15:43 UTC, marcoscaceres commented on index.html
> +          <a>onshippingaddresschange</a> event. This feature enables user
Should probably change: 

> `associated with the <a>onshippingaddresschange</a> event.`
 
used in the creation of `<a>`physical addresses`</a>` throughout the API.

Then that should cover us for when I add the billing address stuff

2018-06-28 16:27 UTC, ianbjacobs commented on index.html
> +          <a>onshippingaddresschange</a> event. This feature enables user
I've made a tweak based on your comment. I also added "tax information" alongside "shipping costs" as an example; that was mentioned in today's call.

2018-07-03 21:13 UTC, marcoscaceres approved these changes

2018-07-03 21:13 UTC, merged