Describe privacy inplications of changing payment method
w3c/browser-payment-api pull request #849
Opened 2019-03-12 03:55 UTC by marcoscaceres

Attempt to address feedback from @wseltzer as part of PING feedback. 

The following tasks have been completed:

 * [X] Confirmed there are no ReSpec errors/warnings.
 * [ ] Has undergone security/privacy review 
 
Optional, impact on Payment Handler spec?

2019-03-12 12:15 UTC, rsolomakhin approved these changes
Looks good from the standpoint of payment handlers. The PH API does not yet have the payment method change event defined, but I will keep this PR in mind when adding it.

2019-03-12 13:29 UTC, ianbjacobs requested changes
Hi Marcos, 

Minor editorial suggestions.

2019-03-12 13:29 UTC, ianbjacobs commented on index.html
> +            A <a>payment handler</a> that define <a>steps for when a user
```suggestion
            A <a>payment handler</a> that defines <a>steps for when a user
```

2019-03-12 13:29 UTC, ianbjacobs commented on index.html
> +          Where sharing of privacy sensitive information might not be obvious
```suggestion
          Where sharing of privacy-sensitive information might not be obvious
```

2019-03-12 13:29 UTC, ianbjacobs commented on index.html
> +          to users (e.g., <a data-lt=
```suggestion
          to users (e.g., when <a data-lt=
```

2019-03-12 13:29 UTC, ianbjacobs commented on index.html
> +          is RECOMMEDED that user agents inform user of exactly what
```suggestion
          is RECOMMENDED that user agents inform the user of exactly what
```

2019-03-13 03:41 UTC, ianbjacobs approved these changes

2019-03-13 04:07 UTC, merged