Remove recommendation to localize sheet based on body element
w3c/browser-payment-api pull request #896
Opened 2020-01-24 05:49 UTC by marcoscaceres

closes #895 

The following tasks have been completed:

 * [x] Confirmed there are no ReSpec errors/warnings.

Optional, impact on Payment Handler spec?

None.

2020-01-24 05:53 UTC, marcoscaceres commented
@janiceshiu, when you can, could you check this to see if it makes sense (and for typos/grammar)? Thanks! 🙏

2020-01-28 07:22 UTC, janiceshiu requested changes
would be lovely to get some things clarified. also suggested some rewordings to make the text clearer ^^

2020-01-28 07:22 UTC, janiceshiu commented on index.html
> +              preference of the user when presenting payment methods.
```suggestion
              user's preference when presenting payment methods.
```
* clearer and shorter wording 
* also - it is not very clear to me what `preferences` users are allowed to have. could you clarify this?

2020-01-28 07:22 UTC, janiceshiu commented on index.html
> +                The API does not provide a means for developers to specify the
```suggestion
                The API does not provide a way for developers to specify the
```
imho `way` is less jargon-y than `means`

2020-01-28 07:22 UTC, janiceshiu commented on index.html
> +                users. As such, user agents will generally present the payment
read through the [show method](https://www.w3.org/TR/payment-request/#show-method). after doing a quick search in that section, I noticed that with one exception, the term `user` is always used. that exception is for `end-user` and it appears here.
https://github.com/w3c/payment-request/blob/fe208dba28724d0a316bf706fbf39cc4414bd8f2/index.html#L1119-L1120
elsewhere in the spec, `end user` is occasionally used.

it is not clear to me what is the difference between a `user` and an `end user`. I did not see linked definitions for `user`, `end-user`, or `end user`. there is, however, a definition for `user agent`.

perhaps we could clarify the difference between a `user` and an `end user`, and decide whether to use `end user` or `end-user`?

2020-01-28 07:22 UTC, janiceshiu commented on index.html
> +                {{PaymentItems}}, in a future version of this API.
```suggestion
The working group is thinking of adding the ability for developers to specify the language for the payment sheet and for specific {{PaymentItems}}. If added, these abilities will be in a future version of this API.
```
* Overall, this is a bit hard to read and understand. I had to read it multiple times. Thus, to make the meaning clearer, I split it into 2 sentences.
* `contemplating adding` is a rather hard to read and understand. probably due to the two successive `-ing` verbs.

2020-01-28 07:22 UTC, janiceshiu commented on index.html
> +                users. As such, user agents will generally present the payment
```suggestion
                users. As such, user agents will generally use the user agent's default language to present the payment sheet.
```
* Sentence was rather hard to read. Have suggested a rewording.
* `generally` doesn't seem to have a particular meaning unlike `SHOULD` and `RECOMMENDED`. In this case, it is not clear how strictly the spec wants user agents to follow the `generally` recommendation. Perhaps we could clarify this?

2020-01-28 07:22 UTC, janiceshiu commented on index.html
> +                specify the language the payment sheet, and of specific
```suggestion
                specify the language of the payment sheet, and of specific
```
Missing a word. ^^ I've also suggested a rewording of the entire sentence in another comment.

2020-02-11 07:51 UTC, marcoscaceres commented on index.html
> +                users. As such, user agents will generally present the payment
end user, I think

2020-02-11 07:55 UTC, marcoscaceres commented on index.html
> +                users. As such, user agents will generally present the payment
Can fix in a follow up.

2020-02-11 07:56 UTC, marcoscaceres commented
@ianbjacobs, over to you for a final read.

2020-02-12 03:40 UTC, ianbjacobs approved these changes

2020-02-12 03:53 UTC, merged