Derive direction from document element too
w3c/browser-payment-api pull request #956
Opened 2021-05-05 06:32 UTC by marcoscaceres

closes #???

The following tasks have been completed:

 * [ ] Confirmed there are no ReSpec errors/warnings.
 * [ ] Modified Web platform tests (link)
 * [ ] Modified MDN Docs (link)
 * [ ] Has undergone security/privacy review (link)
 
Implementation commitment:

 * [ ] Safari (link to issue)
 * [ ] Chrome (link to issue)
 * [ ] Firefox (link to issue)
 * [ ] Edge (public signal)

Optional, impact on Payment Handler spec?

2021-05-05 13:58 UTC, ianbjacobs commented
Hi @marcoscaceres,

Thanks for starting this. Some thoughts:

1) The phrase "payment sheet" is not used elsewhere in the document. I think we should either define it (e.g., by adding "(called the 'payment sheet')" after "Present a user interface" at the beginning of item 18) or remove it. If we remove it, then the note title could become: "Localization of the user interface to interact with handlers". Then you could just s/payment sheet/user interface/ in the note body.

2) Point 18 says "SHOULD use info provided in content. It's not clear to me that the note needs to say "As such, user agents will generally present the payment sheet using the user agent's default language." That to me suggests that despite the recommendation we just made, nobody is doing it.

What about a Note that says:

 "This API relies on inherited localization information. The working group is considering support for fine-grained localization of the user interface and of individual PaymentItems in a future version of this API."

2021-05-10 16:39 UTC, ianbjacobs requested changes
(See my comments above)

2021-05-11 05:13 UTC, marcoscaceres commented
> That to me suggests that despite the recommendation we just made, nobody is doing it.

That's the truth tho :) 

Will update based on your suggestions.

2021-05-11 14:32 UTC, ianbjacobs approved these changes

2021-05-11 14:34 UTC, ianbjacobs commented
@aphillips, would you mind having a look at this proposal to address the lack of fine-grain localization in V1 of the API? Thank you!

2021-05-11 14:55 UTC, aphillips requested changes
Generally looks good. Small tweaks proposed.

2021-05-11 14:55 UTC, aphillips commented on index.html
> +              {{Document/dir}} attribute, if any, or an appropriate fallback
The direction should also be at the Node level, no?

2021-05-11 14:55 UTC, aphillips commented on index.html
> +              locale if that is not available.
Omit `locale` since this is both locale and direction now?

2021-05-11 14:55 UTC, aphillips commented on index.html
> +                localization of the user interface and of individual
I'd probably change "fine-grained" to "control of" (too strong?) or perhaps "requesting  specific"

2021-05-12 06:21 UTC, marcoscaceres commented on index.html
> +              {{Document/dir}} attribute, if any, or an appropriate fallback
It should, but there is no such thing on Node unfortunately:
https://dom.spec.whatwg.org/#node
 
The only "dir"s in the platform are: 
https://respec.org/xref/?term=dir

2021-05-12 06:27 UTC, marcoscaceres commented on index.html
> +              {{Document/dir}} attribute, if any, or an appropriate fallback
Oh, wait... we might be able to use https://html.spec.whatwg.org/multipage/dom.html#the-directionality ... but I'll need to get it "exported" so we can use it in our spec.

2021-05-12 06:37 UTC, marcoscaceres commented on index.html
> +              {{Document/dir}} attribute, if any, or an appropriate fallback
Sent https://github.com/whatwg/html/pull/6676 ...

2021-05-12 14:00 UTC, aphillips commented on index.html
> +              {{Document/dir}} attribute, if any, or an appropriate fallback
@marcoscaceres Thanks. I squinted at `{{HTMLElement/dir}}` and it wasn't clear to me if it included inherited direction. `[^html-global/dir^]` is the definition of the `dir` attribute and includes inheritance, but doesn't seem quite to match our needs here. Exporting `directionality` is a better solution--not just here but generally! I may take whatwg/html#6676 to expedite ;-).

2021-05-12 14:02 UTC, aphillips commented on index.html
> +              {{Document/dir}} attribute, if any, or an appropriate fallback
LOL. I thought 6676 was an issue, but it's a PR...

2021-05-13 03:58 UTC, marcoscaceres commented on index.html
> +              {{Document/dir}} attribute, if any, or an appropriate fallback
@aphillips, take a look at @annevk's comments at https://github.com/whatwg/html/pull/6676 ... I think they make a lot of sense. 

My feeling is that we punt on `dir` for now, and solve this with "localizable" in a future version of the spec.

2021-05-18 12:50 UTC, ianbjacobs commented on index.html
> +              {{Document/dir}} attribute, if any, or an appropriate fallback
@aphillips, would that work for you?

2021-05-18 14:43 UTC, aphillips commented on index.html
> +              {{Document/dir}} attribute, if any, or an appropriate fallback
LGTM.

@marcoscaceres I'm pondering a reply to @annevk: I think he is right, although I18N does want to promote using the document's context when it is available and is appropriate.

2021-05-18 14:43 UTC, aphillips approved these changes

2021-05-20 02:41 UTC, merged