Add internationalization support for human readable labels
w3c/browser-payment-api pull request #971
Opened 2021-10-05 22:12 UTC by ianbjacobs

The Internationalization Working Group has raised concerns about lack of Internationalization support for two strings in the specification (see issues #948 and #951). 

I agree that the specification should support internationalization.

I believe the following is deployment reality:

* In most cases, language context from the document will suffice for the proper representation of the two strings. That is: I believe that explicit metadata for these strings will rarely be needed.
* These strings are either rendered in the browser "sheet" or in "first party" payment apps (e.g., Google Pay and Apple Pay). These strings are not passed to Web-based payment handlers (through Payment Handler API) and, I believe, not passed to "third party" Android native payment handlers.  (There are no third party payment apps with Safari.)
* I also believe that most real-world uses of payment request API involve "skipping" the sheet. That is: calls to Payment Request API involve a single payment method and a single payment app matches, so the browser launches the payment app directly without displaying the sheet. Thus, in practice, rendering these strings in the sheet is rare. 
* In Chrome the sheet has been used as part of built-in support for Basic Card. However, Chrome has signaled that they plan to deprecate their built-in support for Basic Card, so that use of the sheet is likely to go away. The Web Payments Working Group has also retired the Basic Card payment method specification.

Summary: In practice these strings are used almost exclusively used by the Google Pay and Apple Pay native apps. 

Other observations:

* The Web community is working on a platform-wide solution ("Localizable").
* I believe that browser vendors will consider it a low priority to add support for features that will be rarely necessary and for strings that are not directly handled in the browser (but are passed to a small number of native applications).

Given this context, the current pull request seeks a balance:

* Recognize more visibly the need for internationalization support in this specification. Indicate via Candidate Additions [1] that two dictionaries lack "language" and "direction" members. We can continue to work with Google and Apple on support for these features in Google Pay and Apple Pay.
* Indicate that the Working Group is monitoring the Localizable discussion. It may turn out that a platform-wide solution is preferable to a one-off solution; we don't know yet. We have to consider both backward and forward compatibility in determining how to modify the spec in the future.
* Because these features are expected to be used rarely in the near term, allow the specification to advance to Recommendation with the Candidate Additions. 

[Added after posting: if people disagree with the above characterization, please weigh in on that. Thanks!]

I look forward to feedback from @aphillips, @r12a, and the Internationalization Working Group, as well as @marcoscaceres, @stephenmcgruer, @rsolomakhin, and @nickjshearer.

[1] https://www.w3.org/2020/Process-20200915/#candidate-addition

The following tasks have been completed:

 * [✅] Confirmed there are no ReSpec errors/warnings.
 * [ ] Modified Web platform tests (link)
 * [ ] Modified MDN Docs (link)
 
Implementation commitment:

 * [ ] Safari (link to issue)
 * [ ] Chrome (link to issue)
 * [ ] Firefox (link to issue)
 * [ ] Edge (public signal)

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/payment-request/pull/971.html" title="Last updated on Oct 27, 2021, 8:35 PM UTC (8282cae)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/payment-request/971/ee3bd03...8282cae.html" title="Last updated on Oct 27, 2021, 8:35 PM UTC (8282cae)">Diff</a>

2021-10-06 02:29 UTC, marcoscaceres commented on index.html
> +      </div>
```suggestion
      <aside class="correction" id="c1">
        <p>
        <span class="marker">Candidate Correction 1:</span>
         This dictionary might include definitions for optional members `lang` and
        `dir` to indicate the language and text-direction override of {{PaymentItem/label}}. 
        The Working Group is monitoring progress on <a href=
        "https://github.com/whatwg/webidl/issues/1025">
        WebIDL issue 1025</a>. 
        </p>
      </aside>
```

2021-10-06 02:31 UTC, marcoscaceres commented on index.html
> +          </div>
```suggestion

          <aside class="correction" id="c2">
           <p><span class="marker">Candidate Correction 1:</span>
           This dictionary might include definitions for optional members `lang` and
           `dir` to indicate the language and text-direction override of {{PaymentValidationErrors/error}}. 
           The Working Group is monitoring progress on <a href=
            "https://github.com/whatwg/webidl/issues/1025">
             WebIDL issue 1025</a>. 
           </p>
          </aside>
```

2021-10-06 02:37 UTC, marcoscaceres commented on index.html
> +      </div>
My reading of the process document is that these would be classified as "candidate additions", not corrections. 

```suggestion
      <p>
        This specification includes <a href=
        "https://www.w3.org/2020/Process-20200915/#candidate-addition">Candidate
        additions</a>, which are marked in the document.
      </p>
```

2021-10-06 02:39 UTC, marcoscaceres requested changes
I don't think it's sufficient to just state that `dir` and `lang` will, be added... we need to actually specify them properly (I guess that's part of https://github.com/whatwg/webidl/issues/1025). 

We can keep building on this pull request tho.

2021-10-06 03:08 UTC, marcoscaceres commented on index.html
> +        <span class="marker">Candidate Correction 1:</span>
```suggestion
        <span class="marker">Candidate Addition 1:</span>
```

2021-10-06 03:08 UTC, marcoscaceres commented on index.html
> +           <p><span class="marker">Candidate Correction 1:</span>
```suggestion
           <p><span class="marker">Candidate Addition 1:</span>
```

2021-10-06 03:37 UTC, marcoscaceres commented
Here is a concrete plan:
 
 * First: get agreement on platform wide `dir` and `lang` definition in https://github.com/whatwg/webidl/issues/1025
 * Based on https://github.com/whatwg/webidl/issues/1025, update this spec to do whatever we decide there.
 * If it's adding `dir` and `lang`, add them to the spec here.
 * File bugs on implementations to see if we can get implementation commitment (I can jump into WebKit and/or Chromium if needed).

2021-10-06 16:08 UTC, ianbjacobs commented
@marcoscaceres, quick clarification regarding your plan. Are these steps you recommend after publication of the Rec with this pull request integrated?

2021-10-06 20:11 UTC, marcoscaceres commented
After Rec, as these are additions for a Recommendation.

2021-10-07 13:57 UTC, stephenmcgruer approved these changes
I'm ok with this approach. I don't think I agree with [Marcos' comment](https://github.com/w3c/payment-request/pull/971#pullrequestreview-772142951) that we need to include how `lang` and `dir` would work in detail at this point, but I might be persuaded if you can explain your reasoning @marcoscaceres  :)

(I also don't mind if we **do** include details, if Ian wants to do the extra work.)

2021-10-07 14:18 UTC, marcoscaceres commented
> I might be persuaded if you can explain your reasoning @marcoscaceres :)

So, we wouldn't merge this until **after** REC, and we would only merge this if our group's criteria is met: we would fully spec this out, add tests, and get implementation commitment (same as any feature we've added to the spec in the past).

2021-10-07 19:55 UTC, aphillips approved these changes
I think this covers the need to call out a potential change while we figure out whether to make it and what form it should take.

2021-10-07 19:55 UTC, aphillips commented on index.html
> +        `dir` to indicate the language and text-direction override of {{PaymentItem/label}}.
It wouldn't be "text-direction override". It would be better to say "base direction" or "base text-direction".

2021-10-07 19:55 UTC, aphillips commented on index.html
> +           `dir` to indicate the language and text-direction override of {{PaymentValidationErrors/error}}.
same comment as above.

2021-10-07 19:55 UTC, aphillips commented on index.html
> +         This dictionary might include definitions for optional members `lang` and
we generally prefer `language` and `direction` for data values and `lang` and `dir` for attribute values, but changing that would be optional, as there is a certain harmony to using the same names as the HTML attributes. I'd just leave it for now.

2021-10-07 21:09 UTC, ianbjacobs commented on index.html
> +        `dir` to indicate the language and text-direction override of {{PaymentItem/label}}.
Here is my mental model:

* The document (e.g., in the body element) specifies language and base direction for text in the document.
* If the API is called without any dir/lang metadata, the base direction and language come from the document.
* If the API is called with the dir/lang metadata, they override the base direction and language.

I think that's where the "override" text comes from. If that is not the right mental model and we should just say base direction, that will be fine.

2021-10-07 21:09 UTC, ianbjacobs commented on index.html
> +           `dir` to indicate the language and text-direction override of {{PaymentValidationErrors/error}}.
(see above request for clarification)

2021-10-07 23:06 UTC, marcoscaceres commented on index.html
> +        `dir` to indicate the language and text-direction override of {{PaymentItem/label}}.
```suggestion
        `dir` to indicate the language and base direction of the {{PaymentItem/label}} member. 
```

2021-10-07 23:07 UTC, marcoscaceres commented on index.html
> +           `dir` to indicate the language and text-direction override of {{PaymentValidationErrors/error}}.
```suggestion
           `dir` to indicate the language and base direction of the {{PaymentValidationErrors/error}} member. 
```

2021-10-07 23:08 UTC, marcoscaceres commented on index.html
> +        `dir` to indicate the language and text-direction override of {{PaymentItem/label}}.
@aphillips is right... it's the base direction of the label itself.

2021-10-26 17:14 UTC, ianbjacobs commented
Based on joint I18N/WPWG discussion today [1] I anticipate that we will not add dir/lang to Payment Request. I believe there is now support for publishing the Recommendation with informative hooks that indicate that internationalization for these two strings needs to be fixed and that we are part of a Web community discussion about how to do that with a platform-wide solution. I took an action to work with @r12a on text for the specification. 

[1] https://www.w3.org/2021/10/26-wpwg-minutes.html#t03

2021-10-27 18:31 UTC, ianbjacobs commented
@r12a and @aphillips, I have updated this pull request based on the 26 Oct joint discussion. Per @r12a's comments during the meeting, I have characterized this as (1) a fix and (2) pending progress on the platform wide solution. I welcome your review of this and any suggestions.

2021-10-27 20:04 UTC, marcoscaceres approved these changes
I’m approving these, but I’d like to go on the record that I disagree with the additions as they might  set false expectations for readers.

I am broadly supportive of i18n solutions, but if OS-level payment handlers don’t ever end up supporting dir/lang (and there is no implementation backing), then there is not much the W3C or working group can do about that (we can “recommend” things, but we can’t force anyone to implement them). 

I hope that changes in the future through real-world demand. I would have preferred we continue to advocate for the better i18n support as we’ve done with other features in this specification: through close collaboration with implementers and sites/services that are deploying the API at scale.

2021-11-04 16:01 UTC, aphillips approved these changes
The I18N WG reviewed this PR in our teleconference of 2021-11-04 and I drew an [action item](https://www.w3.org/International/track/actions/1092) to approve it.

2021-11-04 16:08 UTC, ianbjacobs commented
@aphillips, many thanks to you and the I18N Working Group for working with us on this and other issues. We really do appreciate the engagement.

2022-01-03 16:04 UTC, merged